### PR TITLE
Add launcher icon for list view

### PR DESCRIPTION
**Pull request by koyuawsmbrtn**
I really like your project so I just thought I'd contribute a little bit. Here's a neat icon for all the list view users.

### CODE REVIEW

**Comment by IdreesInc** [comment]
Hey I really appreciate that, sorry for missing this! To confirm before I can commit this, do you agree to license this image with the MPL open source license this project uses as well as any other license that future releases fall under? Need to be sure of this for assets since I might have to use a different license if this gets posted to the Catalog for instance.

**Comment by koyuawsmbrtn** [comment]
Sure, that work is free to use

**Comment by koyuawsmbrtn** [comment]
Hot GitHub tip: you don't need to ask that every person who will do a pull request. Just create a template with a checkbox people have to tick.

**Comment by IdreesInc** [comment]
Oh nice, thanks for the heads up!

**Pull request merged**
